# Eager execution

In [1]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

In [2]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


In [3]:
print(z.numpy())

121


# Math operations in Tensorflow

In [4]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

In [5]:
sum = tf.add(x,y)
sum.numpy()


array([4., 4., 4.], dtype=float32)

In [6]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

In [7]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

In [8]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

In [9]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

10.0

In [14]:
#Finding index of minimum and maximum elements using argmin and argmax
x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())
print(tf.argmax(x).numpy())

1
2


In [15]:
#Squared difference between x and y
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

In [16]:
#Typecasting: Converting one data type to another
print(x.dtype)

<dtype: 'int32'>


In [17]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [18]:
#Concatenate the two matrices:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

In [19]:
#Rowwise concatenation
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

In [20]:
#Columnwise concatenation
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

In [21]:
#Stacking a matrix
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

In [22]:
#The reduce_mean operation
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

In [23]:
#Computing the overall mean of x
tf.reduce_mean(input_tensor=x).numpy()

2.75

In [24]:
#Computing the mean across the row
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

In [25]:
#Drawing random values from the probability distributions:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.77239406, 0.5885092 ],
       [0.20900548, 0.9787179 ],
       [0.89749324, 0.65896904]], dtype=float32)

In [26]:
#Computing the softmax probabilities
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

**Computing gradients**

In [28]:
#defining a square function
def square(x):
    return tf.multiply(x, x)

In [29]:
#Then we can compute the gradient using tf.Gradienttape
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())

36.0


# Tensorflow 2.0 and Keras

In [30]:
#Defining a Sequential Model
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [31]:
model = Sequential()

In [32]:
model.add(Dense(13, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [33]:
#Defining a functional model
input = tf.keras.Input(shape=(2,))
layer1 = Dense(10, activation='relu')(input)
layer2 = Dense(10, activation='relu')(layer1)
output = Dense(1, activation='sigmoid')(layer2)
model = tf.keras.Model(inputs=input, outputs=output)

In [34]:
#Compiling the model
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

**MNIST digit classification using Tensorflow 2.0**

In [35]:
mnist = tf.keras.datasets.mnist

In [36]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [37]:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)

In [38]:
model = tf.keras.models.Sequential()

In [39]:
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [40]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [41]:
#Model training
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 11s 3ms/step - loss: 0.5958 - accuracy: 0.8448
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2780 - accuracy: 0.9212
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2261 - accuracy: 0.9354
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1919 - accuracy: 0.9452
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1664 - accuracy: 0.9529
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1469 - accuracy: 0.9581
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1308 - accuracy: 0.9627
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1176 - accuracy: 0.9665
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1064 - accuracy: 0.9702
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.09

In [43]:
#Model evaluation
model.evaluate(x_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.1050 - accuracy: 0.9680


[0.10496241599321365, 0.9679999947547913]